const questions=[
["AI Strategy","How clearly is AI connected to your organization's broader strategic priorities?",["We are still exploring what AI could mean for us.","AI is discussed, but clear priorities are not established.","We have identified potential use cases and opportunities.","AI initiatives are aligned with specific business objectives.","AI is integrated into our long-term organizational strategy."]],
["AI Strategy","How does your organization decide which AI initiatives to pursue?",["We have not established a process yet.","Decisions are mostly driven by interest or emerging trends.","We evaluate opportunities based on potential value and feasibility.","We use defined criteria, including impact, risk, and readiness.","We have a structured process for prioritizing and reviewing AI investments."]],
["Data Readiness","How accessible is the data needed to support AI initiatives across your organization?",["Data is largely fragmented across disconnected systems.","We can access some data, but integration remains a challenge.","Key datasets are accessible for selected use cases.","Most priority data sources are connected and accessible.","Our data infrastructure supports organization-wide AI initiatives."]],
["Data Readiness","How confident are you in the quality and reliability of your organization's data?",["Data quality is a significant concern.","Quality varies considerably across systems and departments.","We have quality checks for some important datasets.","Data quality is regularly monitored and managed.","We have data quality standards, ownership, and accountability across the organization."]],
["Governance","How prepared is your organization to address privacy, security, and regulatory requirements when adopting AI?",["We are still understanding what these requirements mean for AI.","We address concerns on a case-by-case basis.","We have started defining policies for AI-related risks.","We have established processes for reviewing AI initiatives.","AI governance is embedded in our processes, with clear accountability."]],
["Governance","Who is accountable for monitoring AI systems after deployment?",["We have not defined ownership yet.","Responsibility usually falls to the implementing team.","Ownership is defined for some AI initiatives.","Designated teams or individuals oversee AI systems.","We have ongoing monitoring, clear ownership, and escalation processes."]],
["Implementation","Where does your organization currently stand in implementing AI?",["We have not started exploring specific applications.","We are researching potential applications.","We are running small-scale experiments or pilots.","We have implemented AI in selected workflows.","AI is used across multiple workflows, with measurable outcomes."]],
["Implementation","How does your organization evaluate whether an AI implementation is successful?",["We have not established success criteria.","We primarily look at whether the technology works.","We evaluate measures such as efficiency or user feedback.","We track defined operational and business outcomes.","We continuously measure outcomes, adoption, risks, and return on investment."]],
["Leadership Alignment","How aligned is your leadership team on the role AI should play?",["There is little discussion about AI at the leadership level.","Interest exists, but perspectives differ significantly.","We have started discussing shared priorities.","Leadership generally agrees on priorities and responsibilities.","AI has clear executive sponsorship and cross-functional alignment."]],
["Leadership Alignment","How prepared are employees to work alongside AI-enabled systems?",["We have not started addressing workforce readiness.","Awareness exists, but structured preparation is limited.","Some teams have received training or exposure.","We have defined training and change-management initiatives.","Workforce readiness is continuously developed alongside AI implementation."]]
];
const dimensions=["AI Strategy","Data Readiness","Governance","Implementation","Leadership Alignment"];
const archetypes=[
["The AI Explorer","Curious, with foundations still taking shape.","Your organization is exploring what AI could mean. The next step is to identify a focused problem and build shared understanding.","Choose one meaningful use case and define what success would look like.","✦"],
["The Strategic Architect","Turning interest into a direction.","Your organization is beginning to connect AI opportunities with business priorities. Clear ownership and prioritization can help turn intent into action.","Agree on a small set of priorities, owners, and measures of success.","⌘"],
["The Governance Guardian","Building trust into the approach.","Your organization is paying attention to the responsibilities that come with AI. Keep governance connected to practical implementation, not separate from it.","Create a review process that brings business, clinical, legal, security, and data teams together.","⬡"],
["The Data Integrator","Working on the foundations AI depends on.","Your organization recognizes the importance of accessible, reliable data. Focus on the data needed for specific workflows rather than trying to connect everything at once.","Map the data required for one priority use case, including its sources, quality, and access.","◇"],
["The AI Pioneer","Moving from pilots into practice.","Your organization is putting AI into use and learning from implementation. Consistent measurement and oversight can help sustain progress.","Track adoption, workflow impact, safety, and ongoing performance after deployment.","➤"],
["The Transformation Catalyst","Connecting AI across the organization.","Your responses suggest AI is becoming part of broader organizational operations. Continue checking that progress is consistent across teams and dimensions.","Review your weakest dimension and make it part of the next enterprise AI planning cycle.","✧"]
];
let answers=Array(10).fill(null),index=0;
const $=id=>document.getElementById(id);
$("start").onclick=()=>{ $("intro").classList.add("hidden");$("quiz").classList.remove("hidden");render();};
function render(){let q=questions[index];$("dimension").textContent=q[0];$("question").textContent=q[1];$("count").textContent=`Question ${index+1} of 10`;$("pct").textContent=`${(index+1)*10}%`;$("bar").style.width=`${(index+1)*10}%`;$("options").innerHTML=q[2].map((o,i)=>`<label class="option ${answers[index]===i+1?'selected':''}"><input type="radio" name="answer" value="${i+1}" ${answers[index]===i+1?'checked':''}>${o}</label>`).join("");document.querySelectorAll('input[name=answer]').forEach(el=>el.onchange=e=>{answers[index]=+e.target.value;render();});$("back").disabled=index===0;$("next").textContent=index===9?"See my result":"Next";$("next").disabled=!answers[index];}
$("back").onclick=()=>{if(index>0){index--;render();}};$("next").onclick=()=>{if(index<9){index++;render();}else showResult();};
function showResult(){const total=answers.reduce((a,b)=>a+b,0);let tier=Math.min(5,Math.floor((total-10)/7));const a=archetypes[tier];$("quiz").classList.add("hidden");$("result").classList.remove("hidden");$("symbol").textContent=a[4];$("archetype").textContent=a[0];$("tagline").textContent=a[1];$("description").textContent=a[2];$("nextstep").textContent=a[3];$("total").textContent=total;$("advice").textContent="Your overall score is only one part of the picture. Review the dimension scores below to see where your organization may want to focus.";
const sums=dimensions.map((d,j)=>answers[j*2]+answers[j*2+1]);$("dimensions").innerHTML=dimensions.map((d,i)=>`<div class="dimension"><div class="dimhead"><span>${d}</span><strong>${sums[i]}/10</strong></div><div class="track"><div class="fill" style="width:${sums[i]*10}%"></div></div></div>`).join("");}
$("share").onclick=()=>{let t=`I got "${$("archetype").textContent}" in the Healthcare AI Leadership Archetype scorecard by Healthcare Unstructured. Take the scorecard and discover your organization's AI profile.`;if(navigator.share)navigator.share({title:"My Healthcare AI Leadership Archetype",text:t});else navigator.clipboard?.writeText(t).then(()=>alert("Share text copied."));};
$("community").onclick=()=>alert("Add your Healthcare Unstructured LinkedIn community URL in script.js.");
$("restart").onclick=()=>{answers=Array(10).fill(null);index=0;$("result").classList.add("hidden");$("intro").classList.remove("hidden");};
